version: '3'
services:
  api:
    environment:
      - API_AUTH_TOKEN_SECRET=dont_tell_anyone
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - ./lib:/app/lib
      - ./bin:/app/bin
      - ./rake:/app/rake
      - .rubocop.yml:/app/.rubocop.yml

